window.TRACEVAULT_DATA = {
  product: {
    name: "RM TraceVault",
    tagline: "Preserve. Protect. Prove.",
    company: "RM TraceVault Information Technology Ltd",
    location: "Riyadh, Saudi Arabia",
    email: "info@tracevault.sa",
    domain: "tracevault.sa",
    version: "Concept Demo 1.0",
  },
  tenants: [
    { id: "alsafa", name: "Al Safa Group", plan: "Professional", storage: 42.81, allowance: 100, users: 64, cases: 342, evidence: 8760000 },
    { id: "najd", name: "Najd Financial Services", plan: "Sovereign Enterprise", storage: 188.4, allowance: 300, users: 126, cases: 97, evidence: 3214000 },
    { id: "riyadhlaw", name: "Riyadh Legal Partners", plan: "Standard", storage: 12.6, allowance: 25, users: 28, cases: 156, evidence: 684200 },
  ],
  packages: [
    {
      id: "standard",
      name: "Evidence Vault — Standard",
      short: "Standard",
      price: 950000,
      onboarding: 150000,
      storage: 25,
      users: 50,
      connectors: 2,
      support: "8×5 Standard",
      overage: 2400,
      description: "Secure foundation for regulated evidence preservation and verification.",
      features: ["WORM preservation", "AES-256-GCM encryption", "SHA-512 verification", "Custody timeline", "Core technical export", "Basic reports"],
    },
    {
      id: "professional",
      name: "Evidence Trust — Professional",
      short: "Professional",
      price: 1850000,
      onboarding: 300000,
      storage: 100,
      users: 150,
      connectors: 5,
      support: "Priority 8×5",
      overage: 1800,
      description: "Advanced workflows for multi-team investigations and governance.",
      features: ["Everything in Standard", "Advanced retention", "Legal Hold", "Case Workspace", "SSO", "Offline verification", "Advanced reporting"],
      popular: true,
    },
    {
      id: "sovereign",
      name: "Sovereign Enterprise",
      short: "Sovereign",
      price: 3750000,
      onboarding: 650000,
      storage: 300,
      users: 500,
      connectors: 10,
      support: "24×7 P1 subject to SLA",
      overage: 1250,
      description: "Sovereign controls and enterprise governance for regulated organizations.",
      features: ["Everything in Professional", "Dedicated tenant controls", "Advanced key custody", "Private connectivity option", "Quarterly service review", "Custom integrations"],
    },
    {
      id: "strategic",
      name: "Strategic Dedicated",
      short: "Strategic",
      price: 6500000,
      onboarding: 1250000,
      storage: 500,
      users: 1000,
      connectors: 20,
      support: "Named service team",
      overage: 900,
      description: "Dedicated design for mission-critical or strategic national workloads.",
      features: ["Dedicated isolation options", "Custom key-custody model", "Custom DR design", "Named operations team", "Custom integrations", "Executive governance"],
    },
  ],
  evidence: [
    {
      id: "EV-2026-005678",
      title: "CCTV_2026_07_30_14_32_11.mp4",
      source: "CCTV / VMS",
      sourceDetail: "Entrance Gate — CAM 04",
      type: "Video",
      mime: "video/mp4",
      size: "2.41 GB",
      sizeGb: 2.41,
      caseId: "CASE-2026-0192",
      caseName: "Unauthorized Access Investigation",
      collected: "30 Jul 2026, 14:32 AST",
      ingested: "30 Jul 2026, 14:33 AST",
      hash: "9f7b2c6e2e1a8f0b4c6d9e7f3a7c2d6f1b3e9a8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: true,
      retention: "30 Jul 2033",
      tags: ["CCTV", "Access", "Priority"],
      actor: "Faisal Al Harbi",
      thumbnail: "assets/cctv-evidence.jpg",
    },
    {
      id: "EV-2026-005679",
      title: "M365_Executive_Mailbox_Export.pst",
      source: "Microsoft 365",
      sourceDetail: "Executive Investigation Hold",
      type: "Email",
      mime: "application/vnd.ms-outlook",
      size: "12.80 GB",
      sizeGb: 12.8,
      caseId: "CASE-2026-0421",
      caseName: "Financial Fraud Investigation",
      collected: "30 Jul 2026, 11:05 AST",
      ingested: "30 Jul 2026, 11:09 AST",
      hash: "8d67f7a823c91e6a3f2d1847c0b9e5f6328a4d9f7b3e1c5a0d8f9b2c6a3e7d4f8c1a9b5e3d7f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6d8",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: true,
      retention: "30 Jul 2033",
      tags: ["M365", "Email", "Finance"],
      actor: "Omar Al Dossari",
    },
    {
      id: "EV-2026-005680",
      title: "Wire_Transfer_Receipt_88421.pdf",
      source: "Files & Folders",
      sourceDetail: "Finance Share",
      type: "Document",
      mime: "application/pdf",
      size: "1.20 MB",
      sizeGb: 0.0012,
      caseId: "CASE-2026-0421",
      caseName: "Financial Fraud Investigation",
      collected: "29 Jul 2026, 09:44 AST",
      ingested: "29 Jul 2026, 09:45 AST",
      hash: "78fac1e9b3d57a9c2e4b6d8f0a1c3e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6d8f0a1c3e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: false,
      retention: "29 Jul 2031",
      tags: ["Finance", "Receipt", "PDF"],
      actor: "Sarah Al Qahtani",
    },
    {
      id: "EV-2026-005681",
      title: "login-attempts-2026-07-29.log",
      source: "SIEM / Syslog",
      sourceDetail: "Microsoft Sentinel",
      type: "Log",
      mime: "text/plain",
      size: "2.40 MB",
      sizeGb: 0.0024,
      caseId: "CASE-2026-0192",
      caseName: "Unauthorized Access Investigation",
      collected: "29 Jul 2026, 08:15 AST",
      ingested: "29 Jul 2026, 08:15 AST",
      hash: "3a91b7d20f4c6e8a1b3d5f7c9e2a4b6d8f0c1e3a5b7d9f2c4e6a8b0d1f3c5e7a9b2d4f6c8e0a1b3d5f7c9e2a4b6d8f0c1e3a5b7d9f2c4e6a8b0d1f3c5e7a9b",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: false,
      retention: "29 Jul 2031",
      tags: ["Security", "SIEM", "Log"],
      actor: "Ingestion Service",
    },
    {
      id: "EV-2026-005682",
      title: "Forensic_Image_Laptop_07.E01",
      source: "Manual Upload",
      sourceDetail: "Forensics Workstation",
      type: "Disk Image",
      mime: "application/octet-stream",
      size: "42.81 GB",
      sizeGb: 42.81,
      caseId: "CASE-2026-0510",
      caseName: "Internal Device Examination",
      collected: "28 Jul 2026, 16:02 AST",
      ingested: "28 Jul 2026, 16:19 AST",
      hash: "9c12aa783e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6d8f0a1c3e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: true,
      retention: "28 Jul 2036",
      tags: ["Forensic", "Disk Image", "Legal Hold"],
      actor: "Noura Al Qasimi",
    },
    {
      id: "EV-2026-005683",
      title: "Database_Export_FixedAssets_202607.csv",
      source: "Database Export",
      sourceDetail: "Oracle ERP",
      type: "Dataset",
      mime: "text/csv",
      size: "486 MB",
      sizeGb: 0.486,
      caseId: "CASE-2026-0622",
      caseName: "Fixed Assets Reconciliation",
      collected: "27 Jul 2026, 22:00 AST",
      ingested: "27 Jul 2026, 22:03 AST",
      hash: "e1b30d9f5a7c9e2b4d6f8a0c1e3b5d7f9a2c4e6b8d0f1a3c5e7b9d2f4a6c8e0b1d3f5a7c9e2b4d6f8a0c1e3b5d7f9a2c4e6b8d0f1a3c5e7b9d2f4a6c8",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: false,
      retention: "27 Jul 2031",
      tags: ["ERP", "CSV", "Assets"],
      actor: "API Key svc_oracle",
    },
  ],
  cases: [
    { id: "CASE-2026-0421", name: "Financial Fraud Investigation", owner: "Sarah Al Qahtani", status: "Active", evidence: 3724, alerts: 2, exports: 1, priority: "High", updated: "2h ago" },
    { id: "CASE-2026-0192", name: "Unauthorized Access Investigation", owner: "Faisal Al Harbi", status: "Active", evidence: 1284, alerts: 1, exports: 0, priority: "Critical", updated: "4h ago" },
    { id: "CASE-2026-0510", name: "Internal Device Examination", owner: "Noura Al Qasimi", status: "Under Review", evidence: 428, alerts: 0, exports: 2, priority: "Medium", updated: "Yesterday" },
    { id: "CASE-2026-0622", name: "Fixed Assets Reconciliation", owner: "Omar Al Dossari", status: "Active", evidence: 876, alerts: 0, exports: 0, priority: "Medium", updated: "2d ago" },
  ],
  connectors: [
    { id: "cctv", name: "CCTV / VMS", status: "Connected", detail: "3 sources", volume: "312.4 GB", icon: "camera" },
    { id: "files", name: "Files & Folders", status: "Connected", detail: "8 watch paths", volume: "128.7 GB", icon: "folder" },
    { id: "m365", name: "Microsoft 365 Email", status: "Pending Setup", detail: "Connect tenant", volume: "94.2 GB", icon: "mail" },
    { id: "siem", name: "SIEM / Syslog", status: "Connected", detail: "2 endpoints", volume: "51.9 GB", icon: "shield" },
    { id: "api", name: "Secure API", status: "Connected", detail: "5 keys", volume: "37.6 GB", icon: "code" },
    { id: "database", name: "Database Export", status: "Syncing", detail: "1 connection", volume: "22.1 GB", icon: "database" },
    { id: "manual", name: "Manual Upload", status: "Ready", detail: "Drag & drop", volume: "—", icon: "upload" },
  ],
  users: [
    { name: "Faisal Al Harbi", email: "faisal.harbi@alsafa.sa", role: "Platform Admin", mfa: "Verified", last: "Today, 10:18" },
    { name: "Noura Al Qasimi", email: "noura.qasimi@alsafa.sa", role: "Investigator", mfa: "Verified", last: "Today, 09:42" },
    { name: "Omar Bin Talal", email: "omar.talal@alsafa.sa", role: "Auditor", mfa: "Verified", last: "Yesterday, 18:31" },
    { name: "Lina Al Mutairi", email: "lina.mutairi@alsafa.sa", role: "Investigator", mfa: "Not Enrolled", last: "29 Jul 2026" },
    { name: "Saud Al Dossari", email: "saud.dossari@alsafa.sa", role: "Tenant Admin", mfa: "Verified", last: "28 Jul 2026" },
    { name: "Guest Reviewer", email: "guest.reviewer@alsafa.sa", role: "Guest", mfa: "N/A", last: "26 Jul 2026" },
  ],
  exports: [
    { id: "EXP-2026-0730-0017", name: "CASE-2026-0421_Technical_Package", requestor: "Faisal Al Harbi", created: "30 Jul 2026, 10:42", destination: "Secure Download", size: "22.47 GB", verification: "Ready", status: "Complete" },
    { id: "EXP-2026-0729-0012", name: "CASE-2026-0408_Export", requestor: "Sarah Al Qahtani", created: "29 Jul 2026, 16:15", destination: "Sovereign Object Storage", size: "18.92 GB", verification: "Verified", status: "Delivered" },
    { id: "EXP-2026-0728-0009", name: "CASE-2026-0401_Export", requestor: "Ahmed bin Saud", created: "28 Jul 2026, 11:03", destination: "External Media", size: "31.14 GB", verification: "Ready", status: "Complete" },
  ],
  recentActivity: [
    { time: "Today, 10:42", event: "Upload completed", detail: "CCTV — Entrance Gate (2.41 GB)", badge: "CASE-2026-0192", tone: "success" },
    { time: "Today, 09:18", event: "Hash verification passed", detail: "2,341 evidence items verified (SHA-512)", badge: "Automated", tone: "purple" },
    { time: "Yesterday, 18:33", event: "Custody transferred", detail: "From Faisal Al Harbi to Sarah Al Qahtani", badge: "CASE-2026-0421", tone: "warning" },
    { time: "Yesterday, 15:11", event: "Legal hold applied", detail: "Hold LH-2026-0027 on 1.2M evidence records", badge: "Active Hold", tone: "warning" },
    { time: "28 Jul, 11:07", event: "Technical package generated", detail: "Offline-verifiable export (22.47 GB)", badge: "EXP-2026-0009", tone: "teal" },
  ],
  notifications: [
    { title: "Custody alert", text: "Two evidence transfers require review.", time: "8 min ago" },
    { title: "Connector pending", text: "Microsoft 365 connector requires tenant consent.", time: "34 min ago" },
    { title: "Verification complete", text: "Batch 2026-0730 passed integrity validation.", time: "1h ago" },
  ],
  architecture: [
    { id: "edge", name: "Secure Edge", products: "WAF · CLB · EIP", purpose: "Protected access to portal and API", status: "Mapped" },
    { id: "network", name: "Private Network", products: "VPC · NAT · VPN · Cloud Firewall", purpose: "Segmentation, controlled egress and admin access", status: "Mapped" },
    { id: "compute", name: "Application Platform", products: "Compute / Container Target", purpose: "Portal, APIs, workers and integration services", status: "Design decision open" },
    { id: "keys", name: "Key Custody", products: "KMS root · Vault custody", purpose: "Protect tenant data-encryption keys", status: "Profile defined" },
    { id: "evidence", name: "Immutable Evidence Vault", products: "OSS WORM · Versioning", purpose: "Immutable evidence preservation", status: "PoC validated / production evidence pending" },
    { id: "dr", name: "Recovery Layer", products: "Backup · DR object storage", purpose: "Recovery and continuity", status: "Implementation scope open" },
  ],
};
