window.TRACEVAULT_DEMO = {
  product: {
    name: "RM TraceVault",
    descriptor: "Saudi Sovereign Digital Evidence Custody Platform",
    tagline: "LEGAL MEMORY. SEALED FOREVER.",
    pillars: ["WHO", "WHEN", "WHAT", "INTEGRITY", "IMMUTABILITY"],
    environment: "Public Concept Demonstration",
    region: "Saudi Arabia",
    domain: "tracevault.sa",
    version: "Enterprise Demo 3.0"
  },
  tenant: {
    id: "TEN-DEMO-ALPHA",
    name: "Demo Organization Alpha",
    plan: "Sovereign Enterprise",
    region: "Saudi Arabia",
    storageUsed: 188.4,
    storageAllowance: 300,
    users: 126,
    activeCases: 97,
    evidenceObjects: 3214872,
    integrityRate: 100,
    legalHolds: 31,
    pendingExports: 4
  },
  evidence: [
    {
      id: "EV-DEMO-0001",
      title: "CCTV_Entrance_2026-07-30_14-32-11.mp4",
      source: "CCTV / VMS",
      sourceDetail: "Demo Facility — Entrance Camera 04",
      type: "Video",
      mime: "video/mp4",
      size: "2.41 GB",
      caseId: "CASE-DEMO-0192",
      caseName: "Unauthorized Access Review",
      collected: "30 Jul 2026, 14:32 AST",
      ingested: "30 Jul 2026, 14:33 AST",
      verified: "30 Jul 2026, 14:34 AST",
      hash: "9f7b2c6e2e1a8f0b4c6d9e7f3a7c2d6f1b3e9a8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0",
      encryption: "AES-256-GCM / 64 MiB chunks",
      worm: "Object Lock — Compliance Mode",
      integrity: "Verified",
      signature: "Ed25519 custody signature valid",
      legalHold: true,
      retention: "30 Jul 2033",
      actor: "Demo Investigator A",
      trustScore: 100,
      status: "Protected",
      tags: ["CCTV", "Access", "Priority"],
      custody: [
        { seq: 1, time: "30 Jul 2026, 14:32:11 AST", action: "Collected at source", actor: "Connector: CCTV-VMS-04", detail: "Source frame sequence and camera metadata captured.", status: "Signed" },
        { seq: 2, time: "30 Jul 2026, 14:32:18 AST", action: "Ingestion session created", actor: "Secure Ingestion Service", detail: "Evidence ID reserved and tenant authorization validated.", status: "Signed" },
        { seq: 3, time: "30 Jul 2026, 14:33:02 AST", action: "Encrypted", actor: "Encryption Worker", detail: "Per-evidence DEK applied using the approved chunk profile.", status: "Signed" },
        { seq: 4, time: "30 Jul 2026, 14:33:24 AST", action: "Immutable commit completed", actor: "Evidence Vault Service", detail: "Object committed under Compliance Mode retention.", status: "Signed" },
        { seq: 5, time: "30 Jul 2026, 14:34:05 AST", action: "Integrity verification passed", actor: "Verification Service", detail: "Whole-evidence SHA-512 matched the registered manifest.", status: "Signed" },
        { seq: 6, time: "31 Jul 2026, 09:18:42 AST", action: "Viewed by authorized investigator", actor: "Demo Investigator A", detail: "Read-only access granted under case authorization.", status: "Signed" },
        { seq: 7, time: "31 Jul 2026, 11:04:10 AST", action: "Legal Hold applied", actor: "Demo Legal Reviewer", detail: "Retention expiry suspended for the active case.", status: "Signed" }
      ]
    },
    {
      id: "EV-DEMO-0002",
      title: "Executive_Mailbox_Export.pst",
      source: "Microsoft 365",
      sourceDetail: "Demo Executive Mailbox",
      type: "Email",
      mime: "application/vnd.ms-outlook",
      size: "12.80 GB",
      caseId: "CASE-DEMO-0421",
      caseName: "Financial Activity Review",
      collected: "30 Jul 2026, 11:05 AST",
      ingested: "30 Jul 2026, 11:09 AST",
      verified: "30 Jul 2026, 11:12 AST",
      hash: "8d67f7a823c91e6a3f2d1847c0b9e5f6328a4d9f7b3e1c5a0d8f9b2c6a3e7d4f8c1a9b5e3d7f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6d8",
      encryption: "AES-256-GCM / 64 MiB chunks",
      worm: "Object Lock — Compliance Mode",
      integrity: "Verified",
      signature: "Ed25519 custody signature valid",
      legalHold: true,
      retention: "30 Jul 2033",
      actor: "Demo Investigator B",
      trustScore: 100,
      status: "Protected",
      tags: ["Email", "M365", "Legal Hold"],
      custody: [
        { seq: 1, time: "30 Jul 2026, 11:05:00 AST", action: "Collection job authorized", actor: "Demo Tenant Administrator", detail: "Mailbox export scope approved.", status: "Signed" },
        { seq: 2, time: "30 Jul 2026, 11:09:31 AST", action: "Export received", actor: "M365 Evidence Connector", detail: "Transfer manifest and source metadata captured.", status: "Signed" },
        { seq: 3, time: "30 Jul 2026, 11:10:04 AST", action: "Encrypted", actor: "Encryption Worker", detail: "Per-evidence DEK applied.", status: "Signed" },
        { seq: 4, time: "30 Jul 2026, 11:11:22 AST", action: "Immutable commit completed", actor: "Evidence Vault Service", detail: "Object Lock retention activated.", status: "Signed" },
        { seq: 5, time: "30 Jul 2026, 11:12:08 AST", action: "Integrity verification passed", actor: "Verification Service", detail: "SHA-512 matched.", status: "Signed" }
      ]
    },
    {
      id: "EV-DEMO-0003",
      title: "Payment_Document_88421.pdf",
      source: "Files & Folders",
      sourceDetail: "Demo Finance Repository",
      type: "Document",
      mime: "application/pdf",
      size: "1.20 MB",
      caseId: "CASE-DEMO-0421",
      caseName: "Financial Activity Review",
      collected: "29 Jul 2026, 09:44 AST",
      ingested: "29 Jul 2026, 09:45 AST",
      verified: "29 Jul 2026, 09:45 AST",
      hash: "78fac1e9b3d57a9c2e4b6d8f0a1c3e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6d8f0a1c3e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c",
      encryption: "AES-256-GCM / 64 MiB chunks",
      worm: "Object Lock — Compliance Mode",
      integrity: "Verified",
      signature: "Ed25519 custody signature valid",
      legalHold: false,
      retention: "29 Jul 2031",
      actor: "Demo Investigator C",
      trustScore: 100,
      status: "Protected",
      tags: ["Document", "Finance", "PDF"],
      custody: [
        { seq: 1, time: "29 Jul 2026, 09:44:01 AST", action: "File selected", actor: "Demo Investigator C", detail: "Source path and file metadata captured.", status: "Signed" },
        { seq: 2, time: "29 Jul 2026, 09:45:05 AST", action: "Validation passed", actor: "Secure Ingestion Service", detail: "Format, size and authorization checks passed.", status: "Signed" },
        { seq: 3, time: "29 Jul 2026, 09:45:20 AST", action: "Immutable commit completed", actor: "Evidence Vault Service", detail: "Protected object registered.", status: "Signed" },
        { seq: 4, time: "29 Jul 2026, 09:45:32 AST", action: "Integrity verification passed", actor: "Verification Service", detail: "SHA-512 matched.", status: "Signed" }
      ]
    },
    {
      id: "EV-DEMO-0004",
      title: "security-login-events-2026-07-29.log",
      source: "SIEM / Syslog",
      sourceDetail: "Demo Security Analytics",
      type: "Log",
      mime: "text/plain",
      size: "2.40 MB",
      caseId: "CASE-DEMO-0192",
      caseName: "Unauthorized Access Review",
      collected: "29 Jul 2026, 08:15 AST",
      ingested: "29 Jul 2026, 08:15 AST",
      verified: "29 Jul 2026, 08:16 AST",
      hash: "3a91b7d20f4c6e8a1b3d5f7c9e2a4b6d8f0c1e3a5b7d9f2c4e6a8b0d1f3c5e7a9b2d4f6c8e0a1b3d5f7c9e2a4b6d8f0c1e3a5b7d9f2c4e6a8b0d1f3c5e7a9b",
      encryption: "AES-256-GCM / 64 MiB chunks",
      worm: "Object Lock — Compliance Mode",
      integrity: "Verified",
      signature: "Ed25519 custody signature valid",
      legalHold: false,
      retention: "29 Jul 2031",
      actor: "Secure Connector Service",
      trustScore: 100,
      status: "Protected",
      tags: ["Security", "Log", "SIEM"],
      custody: [
        { seq: 1, time: "29 Jul 2026, 08:15:00 AST", action: "Stream checkpoint recorded", actor: "SIEM Connector", detail: "Source offset and sequence registered.", status: "Signed" },
        { seq: 2, time: "29 Jul 2026, 08:15:18 AST", action: "Encrypted and committed", actor: "Evidence Vault Service", detail: "Protected object registered.", status: "Signed" },
        { seq: 3, time: "29 Jul 2026, 08:16:01 AST", action: "Integrity verification passed", actor: "Verification Service", detail: "SHA-512 matched.", status: "Signed" }
      ]
    },
    {
      id: "EV-DEMO-0005",
      title: "Forensic_Image_Workstation_07.E01",
      source: "Manual Upload",
      sourceDetail: "Demo Forensics Workstation",
      type: "Disk Image",
      mime: "application/octet-stream",
      size: "42.81 GB",
      caseId: "CASE-DEMO-0510",
      caseName: "Internal Device Examination",
      collected: "28 Jul 2026, 16:02 AST",
      ingested: "28 Jul 2026, 16:19 AST",
      verified: "28 Jul 2026, 16:21 AST",
      hash: "9c12aa783e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6d8f0a1c3e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6",
      encryption: "AES-256-GCM / 64 MiB chunks",
      worm: "Object Lock — Compliance Mode",
      integrity: "Verified",
      signature: "Ed25519 custody signature valid",
      legalHold: true,
      retention: "28 Jul 2036",
      actor: "Demo Forensic Examiner",
      trustScore: 100,
      status: "Protected",
      tags: ["Forensic", "Disk Image", "Legal Hold"],
      custody: [
        { seq: 1, time: "28 Jul 2026, 16:02:00 AST", action: "Forensic image acquired", actor: "Demo Forensic Examiner", detail: "Acquisition workstation and source media identifiers recorded.", status: "Signed" },
        { seq: 2, time: "28 Jul 2026, 16:19:40 AST", action: "Multipart upload completed", actor: "Secure Ingestion Service", detail: "All chunks present and ordered.", status: "Signed" },
        { seq: 3, time: "28 Jul 2026, 16:20:33 AST", action: "Immutable commit completed", actor: "Evidence Vault Service", detail: "Protected object registered.", status: "Signed" },
        { seq: 4, time: "28 Jul 2026, 16:21:09 AST", action: "Integrity verification passed", actor: "Verification Service", detail: "Whole-image SHA-512 matched.", status: "Signed" },
        { seq: 5, time: "28 Jul 2026, 16:25:00 AST", action: "Legal Hold applied", actor: "Demo Legal Reviewer", detail: "Case preservation hold activated.", status: "Signed" }
      ]
    }
  ],
  connectors: [
    { name: "CCTV / VMS", icon: "camera", status: "Connected", detail: "3 approved sources", volume: "312.4 GB", health: 100 },
    { name: "Files & Folders", icon: "folder", status: "Connected", detail: "8 monitored paths", volume: "128.7 GB", health: 100 },
    { name: "Microsoft 365", icon: "mail", status: "Ready", detail: "Demo connector", volume: "94.2 GB", health: 100 },
    { name: "SIEM / Syslog", icon: "activity", status: "Connected", detail: "2 endpoints", volume: "51.9 GB", health: 99.9 },
    { name: "Secure API", icon: "code", status: "Connected", detail: "5 demo clients", volume: "37.6 GB", health: 100 },
    { name: "Manual Upload", icon: "upload", status: "Ready", detail: "Resumable upload", volume: "—", health: 100 }
  ],
  cases: [
    { id: "CASE-DEMO-0421", name: "Financial Activity Review", owner: "Demo Investigator B", status: "Active", evidence: 3724, alerts: 2, exports: 1, priority: "High", updated: "2 hours ago" },
    { id: "CASE-DEMO-0192", name: "Unauthorized Access Review", owner: "Demo Investigator A", status: "Active", evidence: 1284, alerts: 1, exports: 0, priority: "Critical", updated: "4 hours ago" },
    { id: "CASE-DEMO-0510", name: "Internal Device Examination", owner: "Demo Forensic Examiner", status: "Under Review", evidence: 428, alerts: 0, exports: 2, priority: "Medium", updated: "Yesterday" }
  ],
  activity: [
    { time: "11:04", action: "Legal Hold applied", subject: "EV-DEMO-0001", actor: "Demo Legal Reviewer", tone: "blue" },
    { time: "10:42", action: "Verification package generated", subject: "EXP-DEMO-0017", actor: "Demo Investigator A", tone: "green" },
    { time: "09:18", action: "Evidence viewed", subject: "EV-DEMO-0001", actor: "Demo Investigator A", tone: "gray" },
    { time: "08:51", action: "Integrity verification passed", subject: "EV-DEMO-0004", actor: "Verification Service", tone: "green" },
    { time: "08:15", action: "SIEM batch committed", subject: "BATCH-DEMO-0072", actor: "Secure Connector Service", tone: "blue" }
  ],
  exports: [
    { id: "EXP-DEMO-0017", caseId: "CASE-DEMO-0421", evidence: 14, size: "22.47 GB", created: "30 Jul 2026, 10:42 AST", requestedBy: "Demo Investigator A", status: "Verification Ready" },
    { id: "EXP-DEMO-0012", caseId: "CASE-DEMO-0192", evidence: 6, size: "4.88 GB", created: "29 Jul 2026, 15:09 AST", requestedBy: "Demo Investigator B", status: "Complete" },
    { id: "EXP-DEMO-0008", caseId: "CASE-DEMO-0510", evidence: 3, size: "42.83 GB", created: "28 Jul 2026, 17:20 AST", requestedBy: "Demo Forensic Examiner", status: "Complete" }
  ],
  users: [
    { name: "Demo Tenant Administrator", role: "Tenant Admin", mfa: "Verified", last: "Today, 10:18", access: "Privileged" },
    { name: "Demo Investigator A", role: "Investigator", mfa: "Verified", last: "Today, 09:42", access: "Case-scoped" },
    { name: "Demo Legal Reviewer", role: "Legal Reviewer", mfa: "Verified", last: "Yesterday, 18:31", access: "Hold approvals" },
    { name: "Demo External Reviewer", role: "Guest Reviewer", mfa: "Verified", last: "29 Jul 2026", access: "Time-limited" }
  ],
  controls: [
    { name: "Immutable Evidence Vault", status: "Healthy", detail: "Compliance Mode policy active", icon: "lock" },
    { name: "Integrity Verification", status: "Healthy", detail: "SHA-512 verification service", icon: "fingerprint" },
    { name: "Tenant Isolation", status: "Healthy", detail: "Authorization filters enforced", icon: "building" },
    { name: "Key Custody", status: "Healthy", detail: "KMS-rooted custody controls", icon: "key" },
    { name: "MFA & RBAC", status: "Healthy", detail: "Step-up for sensitive actions", icon: "users" },
    { name: "Audit & Custody Signing", status: "Healthy", detail: "Signed custody events", icon: "shield-check" }
  ],
  editions: [
    { name: "Evidence Vault", label: "Foundation", description: "Core evidence preservation, integrity verification and custody timeline.", features: ["Immutable evidence preservation", "SHA-512 verification", "Chain of custody", "Core technical export", "Tenant RBAC"] },
    { name: "Evidence Trust", label: "Professional", description: "Advanced investigation, legal hold, SSO and offline verification workflows.", features: ["Everything in Evidence Vault", "Case Workspace", "Legal Hold", "Enterprise SSO", "Offline verification", "Advanced reporting"] },
    { name: "Sovereign Enterprise", label: "Regulated", description: "Enhanced governance and sovereign controls for regulated organizations.", features: ["Everything in Evidence Trust", "Advanced key custody", "Private connectivity option", "Service governance", "Custom integrations", "Enhanced support model"] },
    { name: "Strategic Dedicated", label: "Mission Critical", description: "Dedicated architecture options for strategic and large-scale workloads.", features: ["Dedicated isolation options", "Custom custody model", "Custom recovery design", "Named service team", "Executive governance", "Custom acceptance plan"] }
  ]
};