window.TRACEVAULT_DEMO = {
  product: {
    name: "RM TraceVault",
    tagline: "SECURE · TRACE · PROTECT",
    promise: "Preserve the Evidence. Preserve the Trust.",
    description: "A sovereign digital evidence custody platform designed to preserve integrity, custody and independent verification throughout the evidence lifecycle.",
    location: "Riyadh, Saudi Arabia",
    email: "info@tracevault.sa",
    website: "tracevault.sa",
    version: "Enterprise Concept Demo 2.0"
  },
  tenant: {
    id: "demo-org-alpha",
    name: "Demo Organization Alpha",
    sector: "Regulated Enterprise",
    plan: "Sovereign Enterprise",
    storageUsed: 188.4,
    storageLimit: 300,
    users: 126,
    activeCases: 97,
    evidenceCount: 3214000,
    dataRegion: "Saudi Arabia"
  },
  kpis: [
    { label: "Evidence objects", value: "3.21M", delta: "+6.8%", trend: "up", icon: "database" },
    { label: "Verified integrity", value: "99.998%", delta: "Last 30 days", trend: "flat", icon: "shield-check" },
    { label: "Active cases", value: "97", delta: "14 high priority", trend: "up", icon: "briefcase" },
    { label: "Legal holds", value: "31", delta: "0 overdue reviews", trend: "flat", icon: "scale" },
    { label: "Storage used", value: "188.4 TB", delta: "62.8% of plan", trend: "flat", icon: "hard-drive" },
    { label: "Export packages", value: "428", delta: "37 this month", trend: "up", icon: "package" }
  ],
  evidence: [
    {
      id: "EV-DEMO-0001",
      title: "CCTV_Gate_04_2026-07-30.mp4",
      source: "CCTV / VMS",
      sourceDetail: "Main Entrance — Camera 04",
      type: "Video",
      size: "2.41 GB",
      caseId: "CASE-DEMO-0192",
      caseName: "Unauthorized Access Review",
      collected: "30 Jul 2026, 14:32 AST",
      ingested: "30 Jul 2026, 14:33 AST",
      hash: "9f7b2c6e2e1a8f0b4c6d9e7f3a7c2d6f1b3e9a8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: true,
      retention: "30 Jul 2033",
      actor: "Demo Investigator A",
      tags: ["CCTV", "Access", "Priority"],
      status: "Protected"
    },
    {
      id: "EV-DEMO-0002",
      title: "Mailbox_Export_Investigation.pst",
      source: "Enterprise Email",
      sourceDetail: "Investigation Hold Export",
      type: "Email",
      size: "12.80 GB",
      caseId: "CASE-DEMO-0421",
      caseName: "Financial Activity Review",
      collected: "30 Jul 2026, 11:05 AST",
      ingested: "30 Jul 2026, 11:09 AST",
      hash: "8d67f7a823c91e6a3f2d1847c0b9e5f6328a4d9f7b3e1c5a0d8f9b2c6a3e7d4f8c1a9b5e3d7f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6d8",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: true,
      retention: "30 Jul 2033",
      actor: "Demo Investigator B",
      tags: ["Email", "Finance", "Legal Hold"],
      status: "Protected"
    },
    {
      id: "EV-DEMO-0003",
      title: "Transfer_Receipt_88421.pdf",
      source: "Files & Folders",
      sourceDetail: "Finance Evidence Share",
      type: "Document",
      size: "1.20 MB",
      caseId: "CASE-DEMO-0421",
      caseName: "Financial Activity Review",
      collected: "29 Jul 2026, 09:44 AST",
      ingested: "29 Jul 2026, 09:45 AST",
      hash: "78fac1e9b3d57a9c2e4b6d8f0a1c3e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6d8f0a1c3e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: false,
      retention: "29 Jul 2031",
      actor: "Demo Investigator C",
      tags: ["Finance", "Receipt", "PDF"],
      status: "Protected"
    },
    {
      id: "EV-DEMO-0004",
      title: "authentication-events-2026-07-29.log",
      source: "SIEM / Syslog",
      sourceDetail: "Security Monitoring Platform",
      type: "Log",
      size: "2.40 MB",
      caseId: "CASE-DEMO-0192",
      caseName: "Unauthorized Access Review",
      collected: "29 Jul 2026, 08:15 AST",
      ingested: "29 Jul 2026, 08:15 AST",
      hash: "3a91b7d20f4c6e8a1b3d5f7c9e2a4b6d8f0c1e3a5b7d9f2c4e6a8b0d1f3c5e7a9b2d4f6c8e0a1b3d5f7c9e2a4b6d8f0c1e3a5b7d9f2c4e6a8b0d1f3c5e7a9b",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: false,
      retention: "29 Jul 2031",
      actor: "Secure Ingestion Service",
      tags: ["Security", "SIEM", "Log"],
      status: "Protected"
    },
    {
      id: "EV-DEMO-0005",
      title: "Forensic_Image_Device_07.E01",
      source: "Manual Upload",
      sourceDetail: "Forensics Workstation",
      type: "Disk Image",
      size: "42.81 GB",
      caseId: "CASE-DEMO-0510",
      caseName: "Internal Device Examination",
      collected: "28 Jul 2026, 16:02 AST",
      ingested: "28 Jul 2026, 16:19 AST",
      hash: "9c12aa783e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6d8f0a1c3e5b7d9f2a4c6e8b0d1f3a5c7e9b2d4f6a8c0e1b3d5f7a9c2e4b6",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: true,
      retention: "28 Jul 2036",
      actor: "Demo Forensic Analyst",
      tags: ["Forensic", "Disk Image", "Legal Hold"],
      status: "Protected"
    },
    {
      id: "EV-DEMO-0006",
      title: "ERP_Assets_Export_202607.csv",
      source: "Database Export",
      sourceDetail: "Enterprise Resource Platform",
      type: "Dataset",
      size: "486 MB",
      caseId: "CASE-DEMO-0622",
      caseName: "Asset Reconciliation Review",
      collected: "27 Jul 2026, 22:00 AST",
      ingested: "27 Jul 2026, 22:03 AST",
      hash: "e1b30d9f5a7c9e2b4d6f8a0c1e3b5d7f9a2c4e6b8d0f1a3c5e7b9d2f4a6c8e0b1d3f5a7c9e2b4d6f8a0c1e3b5d7f9a2c4e6b8d0f1a3c5e7b9d2f4a6c8",
      encryption: "AES-256-GCM",
      worm: "Compliance Mode",
      integrity: "Verified",
      legalHold: false,
      retention: "27 Jul 2031",
      actor: "API Client · demo-erp",
      tags: ["ERP", "CSV", "Assets"],
      status: "Protected"
    }
  ],
  custody: [
    { action: "Evidence registered", actor: "Secure Ingestion Service", time: "30 Jul 2026, 14:33:02 AST", detail: "Evidence ID issued and source metadata captured." },
    { action: "Integrity fingerprint created", actor: "Integrity Service", time: "30 Jul 2026, 14:33:09 AST", detail: "SHA-512 digest recorded before immutable commit." },
    { action: "Evidence encrypted", actor: "Encryption Service", time: "30 Jul 2026, 14:33:21 AST", detail: "Chunked AES-256-GCM profile applied." },
    { action: "Immutable commit completed", actor: "Evidence Vault", time: "30 Jul 2026, 14:33:34 AST", detail: "Object Lock Compliance Mode confirmed." },
    { action: "Legal Hold applied", actor: "Demo Legal Reviewer", time: "30 Jul 2026, 15:12:40 AST", detail: "Case hold applied with dual approval." },
    { action: "Integrity re-verified", actor: "Demo Investigator A", time: "01 Aug 2026, 10:18:12 AST", detail: "Independent verification completed successfully." }
  ],
  connectors: [
    { name: "CCTV / VMS", status: "Connected", count: "3 sources", volume: "312.4 GB", icon: "camera", tone: "blue" },
    { name: "Files & Folders", status: "Connected", count: "8 watch paths", volume: "128.7 GB", icon: "folder", tone: "cyan" },
    { name: "Enterprise Email", status: "Pending Setup", count: "1 tenant", volume: "94.2 GB", icon: "mail", tone: "purple" },
    { name: "SIEM / Syslog", status: "Connected", count: "2 endpoints", volume: "51.9 GB", icon: "activity", tone: "green" },
    { name: "Secure API", status: "Connected", count: "5 API clients", volume: "37.6 GB", icon: "code", tone: "amber" },
    { name: "Database Export", status: "Syncing", count: "1 connection", volume: "22.1 GB", icon: "server", tone: "blue" },
    { name: "Manual Upload", status: "Ready", count: "Drag & drop", volume: "—", icon: "upload", tone: "cyan" }
  ],
  ingestionQueue: [
    { item: "CCTV_North_Gate_Batch_0812", source: "CCTV / VMS", size: "18.4 GB", validation: "Passed", encryption: "Complete", hash: "Verified", worm: "Committed", owner: "Ingestion Service" },
    { item: "Email_Hold_Export_0421", source: "Enterprise Email", size: "9.8 GB", validation: "Passed", encryption: "Complete", hash: "Verified", worm: "Committed", owner: "Connector Service" },
    { item: "Security_Events_0801", source: "SIEM / Syslog", size: "1.9 GB", validation: "Passed", encryption: "Processing", hash: "Pending", worm: "Pending", owner: "API Client" },
    { item: "Finance_Documents_Batch", source: "Files & Folders", size: "4.2 GB", validation: "Review", encryption: "Pending", hash: "Pending", worm: "Pending", owner: "Demo Investigator C" }
  ],
  cases: [
    { id: "CASE-DEMO-0421", name: "Financial Activity Review", owner: "Demo Investigator B", status: "Active", evidence: 3724, alerts: 2, exports: 1, priority: "High", updated: "2h ago" },
    { id: "CASE-DEMO-0192", name: "Unauthorized Access Review", owner: "Demo Investigator A", status: "Active", evidence: 1284, alerts: 1, exports: 0, priority: "Critical", updated: "4h ago" },
    { id: "CASE-DEMO-0510", name: "Internal Device Examination", owner: "Demo Forensic Analyst", status: "Under Review", evidence: 428, alerts: 0, exports: 2, priority: "Medium", updated: "Yesterday" },
    { id: "CASE-DEMO-0622", name: "Asset Reconciliation Review", owner: "Demo Investigator C", status: "Active", evidence: 876, alerts: 0, exports: 0, priority: "Medium", updated: "2d ago" }
  ],
  users: [
    { name: "Demo Platform Administrator", email: "admin@example.invalid", role: "Platform Admin", mfa: "Verified", access: "Privileged", last: "Today, 10:18" },
    { name: "Demo Investigator A", email: "investigator.a@example.invalid", role: "Investigator", mfa: "Verified", access: "Standard", last: "Today, 09:42" },
    { name: "Demo Compliance Auditor", email: "auditor@example.invalid", role: "Auditor", mfa: "Verified", access: "Read only", last: "Yesterday, 18:31" },
    { name: "Demo Legal Reviewer", email: "legal@example.invalid", role: "Legal Reviewer", mfa: "Verified", access: "Legal Hold", last: "29 Jul 2026" },
    { name: "External Demo Reviewer", email: "guest@example.invalid", role: "External Reviewer", mfa: "Step-up", access: "Time limited", last: "26 Jul 2026" }
  ],
  exports: [
    { id: "EXP-DEMO-0017", name: "CASE-DEMO-0421_Verification_Package", requestor: "Demo Investigator B", created: "30 Jul 2026, 10:42", destination: "Secure Download", size: "22.47 GB", verification: "Ready", status: "Complete" },
    { id: "EXP-DEMO-0012", name: "CASE-DEMO-0510_Review_Package", requestor: "Demo Forensic Analyst", created: "29 Jul 2026, 16:08", destination: "External Reviewer", size: "44.20 GB", verification: "Verified", status: "Complete" },
    { id: "EXP-DEMO-0008", name: "CASE-DEMO-0192_Incident_Package", requestor: "Demo Investigator A", created: "27 Jul 2026, 08:14", destination: "Audit Portal", size: "7.82 GB", verification: "Pending", status: "Processing" }
  ],
  tenants: [
    { name: "Demo Organization Alpha", plan: "Sovereign Enterprise", storage: "188.4 / 300 TB", users: 126, health: "Healthy", region: "Saudi Arabia" },
    { name: "Demo Organization Beta", plan: "Professional", storage: "42.8 / 100 TB", users: 64, health: "Healthy", region: "Saudi Arabia" },
    { name: "Demo Organization Gamma", plan: "Standard", storage: "12.6 / 25 TB", users: 28, health: "Review", region: "Saudi Arabia" }
  ],
  serviceEditions: [
    { name: "Evidence Vault", tier: "Standard", subtitle: "Core preservation and verification", features: ["Immutable evidence vault", "AES-256-GCM encryption", "SHA-512 verification", "Custody timeline", "Core export package", "Standard support"] },
    { name: "Evidence Trust", tier: "Professional", subtitle: "Advanced investigation and governance", features: ["Everything in Standard", "Advanced retention", "Legal Hold", "Case Workspace", "Enterprise SSO", "Offline verification", "Priority support"], featured: true },
    { name: "Sovereign Enterprise", tier: "Enterprise", subtitle: "Sovereign controls for regulated organizations", features: ["Everything in Professional", "Enhanced tenant controls", "Advanced key custody", "Private connectivity option", "Executive governance", "Custom integrations"] },
    { name: "Strategic Dedicated", tier: "Strategic", subtitle: "Dedicated design for mission-critical workloads", features: ["Dedicated isolation options", "Custom custody architecture", "Custom recovery design", "Named service governance", "Bespoke integrations", "Executive operating model"] }
  ],
  architecture: [
    { layer: "Experience", title: "Customer & Reviewer Portals", detail: "Bilingual portals for administrators, investigators, auditors and external reviewers.", components: ["Tenant Portal", "Verify Portal", "Case Workspace", "Admin Console"] },
    { layer: "Application", title: "Evidence Control Services", detail: "Controlled services for ingestion, integrity, custody, retention, legal hold and export.", components: ["Ingestion", "Integrity", "Custody Ledger", "Retention", "Export"] },
    { layer: "Trust", title: "Encryption & Verification", detail: "Chunked encryption, evidence digests, signed custody events and portable verification packages.", components: ["AES-256-GCM", "SHA-512", "Key Custody", "Digital Signatures"] },
    { layer: "Data", title: "Immutable Evidence Vault", detail: "Versioned object storage with WORM controls, metadata and governed lifecycle policies.", components: ["Object Lock", "Versioning", "Metadata", "Search Index"] },
    { layer: "Platform", title: "Sovereign Cloud Foundation", detail: "Target deployment within a Saudi-hosted cloud boundary with monitored security controls.", components: ["Network Segmentation", "WAF", "Monitoring", "Backup & Recovery"] },
    { layer: "Governance", title: "Operational & Compliance Controls", detail: "Access reviews, security operations, change management and acceptance evidence.", components: ["RBAC", "MFA", "Audit", "Service Management"] }
  ]
};
