// RM TraceVault public concept-demo data. All organizations, people, cases and evidence records are fictional.
window.TRACEVAULT_DEMO = {
  product: {
    name: "RM TraceVault",
    descriptor: "Saudi Sovereign Digital Evidence Custody Platform",
    tagline: "LEGAL MEMORY. SEALED FOREVER.",
    pillars: ["WHO", "WHEN", "WHAT", "INTEGRITY", "IMMUTABILITY"],
    environment: "Public Concept Demonstration",
    region: "Saudi Arabia",
    domain: "tracevault.sa"
  },
  tenant: {
    id: "TEN-DEMO-ALPHA",
    name: "Demo Organization Alpha",
    plan: "Sovereign Enterprise",
    region: "Saudi Arabia",
    storageUsed: 188.4,
    storageAllowance: 300,
    users: 126,
    activeCases: 97,
    evidenceObjects: 3214872,
    integrityRate: 100,
    legalHolds: 31,
    pendingExports: 4
  },
  // Generated SHA-512 demonstration values. Each value is exactly 128 hexadecimal characters.
  evidence: [
    {
      id: "EV-DEMO-0001",
      title: "CCTV_Entrance_2026-07-30_14-32-11.mp4",
      source: "CCTV / VMS",
      sourceDetail: "Demo Facility — Entrance Camera 04",
      type: "Video",
      mime: "video/mp4",
      size: "2.41 GB",
      caseId: "CASE-DEMO-0192",
      caseName: "Unauthorized Access Review",
      collected: "30 Jul 2026, 14:32 AST",
      ingested: "30 Jul 2026, 14:33 AST",
      verified: "30 Jul 2026, 14:34 AST",
      hash: "e5ae4b21bb644b8df471aed86d04aecb4bad7f180337ac6d1d0c7cb909b06604eec5e7d34fcbb81809045efda8ad2a85945df2dc3dca512595c2cda1b793e557",
      encryption: "AES-256-GCM / 64 MiB chunks",
      worm: "Object Lock — Compliance Mode",
      integrity: "Verified",
      signature: "Ed25519 custody signature valid",
      timestamp: "RFC 3161 token simulated",
      version: "v1 — immutable original",
      legalHold: true,
      retention: "30 Jul 2033",
      actor: "Demo Investigator A",
      trustScore: 100,
      status: "Protected",
      tags: ["CCTV", "Access", "Priority"],
      custody: [
        { seq: 1, time: "30 Jul 2026, 14:32:11 AST", action: "Collected at source", actor: "Connector: CCTV-VMS-04", detail: "Source frame sequence and camera metadata captured.", status: "Signed" },
        { seq: 2, time: "30 Jul 2026, 14:32:18 AST", action: "Ingestion session created", actor: "Secure Ingestion Service", detail: "Evidence ID reserved and tenant authorization validated.", status: "Signed" },
        { seq: 3, time: "30 Jul 2026, 14:33:02 AST", action: "Encrypted", actor: "Encryption Worker", detail: "Per-evidence DEK applied using the approved chunk profile.", status: "Signed" },
        { seq: 4, time: "30 Jul 2026, 14:33:24 AST", action: "Immutable commit completed", actor: "Evidence Vault Service", detail: "Object committed under Compliance Mode retention.", status: "Signed" },
        { seq: 5, time: "30 Jul 2026, 14:34:05 AST", action: "Integrity verification passed", actor: "Verification Service", detail: "Whole-evidence SHA-512 matched the registered manifest.", status: "Signed" },
        { seq: 6, time: "31 Jul 2026, 09:18:42 AST", action: "Viewed by authorized investigator", actor: "Demo Investigator A", detail: "Read-only access granted under case authorization.", status: "Signed" },
        { seq: 7, time: "31 Jul 2026, 11:04:10 AST", action: "Legal Hold applied", actor: "Demo Legal Reviewer", detail: "Retention expiry suspended for the active case.", status: "Signed" }
      ]
    },
    {
      id: "EV-DEMO-0002",
      title: "Executive_Mailbox_Export.pst",
      source: "Microsoft 365",
      sourceDetail: "Demo Executive Mailbox",
      type: "Email",
      mime: "application/vnd.ms-outlook",
      size: "12.80 GB",
      caseId: "CASE-DEMO-0421",
      caseName: "Financial Activity Review",
      collected: "30 Jul 2026, 11:05 AST",
      ingested: "30 Jul 2026, 11:09 AST",
      verified: "30 Jul 2026, 11:12 AST",
      hash: "ae4f660da3f72be5d9f41e5b2a2d2ad81bee7bba65d69ec60efa694c17dd7c36646741613cd3b1d3b16601c16e709e00f81c79862f78ddf4981aafd4df597f59",
      encryption: "AES-256-GCM / 64 MiB chunks",
      worm: "Object Lock — Compliance Mode",
      integrity: "Verified",
      signature: "Ed25519 custody signature valid",
      timestamp: "RFC 3161 token simulated",
      version: "v1 — immutable original",
      legalHold: true,
      retention: "30 Jul 2033",
      actor: "Demo Investigator B",
      trustScore: 100,
      status: "Protected",
      tags: ["Email", "M365", "Legal Hold"],
      custody: [
        { seq: 1, time: "30 Jul 2026, 11:05:00 AST", action: "Collection job authorized", actor: "Demo Tenant Administrator", detail: "Mailbox export scope approved.", status: "Signed" },
        { seq: 2, time: "30 Jul 2026, 11:09:31 AST", action: "Export received", actor: "M365 Evidence Connector", detail: "Transfer manifest and source metadata captured.", status: "Signed" },
        { seq: 3, time: "30 Jul 2026, 11:10:04 AST", action: "Encrypted", actor: "Encryption Worker", detail: "Per-evidence DEK applied.", status: "Signed" },
        { seq: 4, time: "30 Jul 2026, 11:11:22 AST", action: "Immutable commit completed", actor: "Evidence Vault Service", detail: "Object Lock retention activated.", status: "Signed" },
        { seq: 5, time: "30 Jul 2026, 11:12:08 AST", action: "Integrity verification passed", actor: "Verification Service", detail: "SHA-512 matched.", status: "Signed" }
      ]
    },
    {
      id: "EV-DEMO-0003",
      title: "Payment_Document_88421.pdf",
      source: "Files & Folders",
      sourceDetail: "Demo Finance Repository",
      type: "Document",
      mime: "application/pdf",
      size: "1.20 MB",
      caseId: "CASE-DEMO-0421",
      caseName: "Financial Activity Review",
      collected: "29 Jul 2026, 09:44 AST",
      ingested: "29 Jul 2026, 09:45 AST",
      verified: "29 Jul 2026, 09:45 AST",
      hash: "b184cf91c80f7a4275cc4f2051e175935ac099f04d553d1cb0b48759ad75adf2e402419f4f2426922e67759d259ab1e8657acc094630c76298302ab1c3c0dac4",
      encryption: "AES-256-GCM / 64 MiB chunks",
      worm: "Object Lock — Compliance Mode",
      integrity: "Verified",
      signature: "Ed25519 custody signature valid",
      timestamp: "RFC 3161 token simulated",
      version: "v1 — immutable original",
      legalHold: false,
      retention: "29 Jul 2031",
      actor: "Demo Investigator C",
      trustScore: 100,
      status: "Protected",
      tags: ["Document", "Finance", "PDF"],
      custody: [
        { seq: 1, time: "29 Jul 2026, 09:44:01 AST", action: "File selected", actor: "Demo Investigator C", detail: "Source path and file metadata captured.", status: "Signed" },
        { seq: 2, time: "29 Jul 2026, 09:45:05 AST", action: "Validation passed", actor: "Secure Ingestion Service", detail: "Format, size and authorization checks passed.", status: "Signed" },
        { seq: 3, time: "29 Jul 2026, 09:45:20 AST", action: "Immutable commit completed", actor: "Evidence Vault Service", detail: "Protected object registered.", status: "Signed" },
        { seq: 4, time: "29 Jul 2026, 09:45:32 AST", action: "Integrity verification passed", actor: "Verification Service", detail: "SHA-512 matched.", status: "Signed" }
      ]
    },
    {
      id: "EV-DEMO-0004",
      title: "security-login-events-2026-07-29.log",
      source: "SIEM / Syslog",
      sourceDetail: "Demo Security Analytics",
      type: "Log",
      mime: "text/plain",
      size: "2.40 MB",
      caseId: "CASE-DEMO-0192",
      caseName: "Unauthorized Access Review",
      collected: "29 Jul 2026, 08:15 AST",
      ingested: "29 Jul 2026, 08:15 AST",
      verified: "29 Jul 2026, 08:16 AST",
      hash: "6e5054db1bd72b91f7b6877e697cb975c665c4182a797547aa2999ee605ac45f5f276b6203a3e3aa087173e5edf983d75e722ea5d73233051ebe672204b7b39c",
      encryption: "AES-256-GCM / 64 MiB chunks",
      worm: "Object Lock — Compliance Mode",
      integrity: "Verified",
      signature: "Ed25519 custody signature valid",
      timestamp: "RFC 3161 token simulated",
      version: "v1 — immutable original",
      legalHold: false,
      retention: "29 Jul 2031",
      actor: "Secure Connector Service",
      trustScore: 100,
      status: "Protected",
      tags: ["Security", "Log", "SIEM"],
      custody: [
        { seq: 1, time: "29 Jul 2026, 08:15:00 AST", action: "Stream checkpoint recorded", actor: "SIEM Connector", detail: "Source offset and sequence registered.", status: "Signed" },
        { seq: 2, time: "29 Jul 2026, 08:15:18 AST", action: "Encrypted and committed", actor: "Evidence Vault Service", detail: "Protected object registered.", status: "Signed" },
        { seq: 3, time: "29 Jul 2026, 08:16:01 AST", action: "Integrity verification passed", actor: "Verification Service", detail: "SHA-512 matched.", status: "Signed" }
      ]
    },
    {
      id: "EV-DEMO-0005",
      title: "Forensic_Image_Workstation_07.E01",
      source: "Manual Upload",
      sourceDetail: "Demo Forensics Workstation",
      type: "Disk Image",
      mime: "application/octet-stream",
      size: "42.81 GB",
      caseId: "CASE-DEMO-0510",
      caseName: "Internal Device Examination",
      collected: "28 Jul 2026, 16:02 AST",
      ingested: "28 Jul 2026, 16:19 AST",
      verified: "28 Jul 2026, 16:21 AST",
      hash: "884d08338d60554ee106a7d9ee7da26badb2c122fc1475d1638ed2c4dcd3663f939116191e571a7bce24f2fd8ef51d17096cc9195f82634378500380ab89135d",
      encryption: "AES-256-GCM / 64 MiB chunks",
      worm: "Object Lock — Compliance Mode",
      integrity: "Verified",
      signature: "Ed25519 custody signature valid",
      timestamp: "RFC 3161 token simulated",
      version: "v1 — immutable original",
      legalHold: true,
      retention: "28 Jul 2036",
      actor: "Demo Forensic Examiner",
      trustScore: 100,
      status: "Protected",
      tags: ["Forensic", "Disk Image", "Legal Hold"],
      custody: [
        { seq: 1, time: "28 Jul 2026, 16:02:00 AST", action: "Forensic image acquired", actor: "Demo Forensic Examiner", detail: "Acquisition workstation and source media identifiers recorded.", status: "Signed" },
        { seq: 2, time: "28 Jul 2026, 16:19:40 AST", action: "Multipart upload completed", actor: "Secure Ingestion Service", detail: "All chunks present and ordered.", status: "Signed" },
        { seq: 3, time: "28 Jul 2026, 16:20:33 AST", action: "Immutable commit completed", actor: "Evidence Vault Service", detail: "Protected object registered.", status: "Signed" },
        { seq: 4, time: "28 Jul 2026, 16:21:09 AST", action: "Integrity verification passed", actor: "Verification Service", detail: "Whole-image SHA-512 matched.", status: "Signed" },
        { seq: 5, time: "28 Jul 2026, 16:25:00 AST", action: "Legal Hold applied", actor: "Demo Legal Reviewer", detail: "Case preservation hold activated.", status: "Signed" }
      ]
    }
  ],
  connectors: [
    { name: "CCTV / VMS", icon: "camera", status: "Connected", detail: "3 approved sources", volume: "312.4 GB", health: 100 },
    { name: "Files & Folders", icon: "folder", status: "Connected", detail: "8 monitored paths", volume: "128.7 GB", health: 100 },
    { name: "Microsoft 365", icon: "mail", status: "Ready", detail: "Demo connector", volume: "94.2 GB", health: 100 },
    { name: "SIEM / Syslog", icon: "activity", status: "Connected", detail: "2 endpoints", volume: "51.9 GB", health: 99.9 },
    { name: "Secure API", icon: "code", status: "Connected", detail: "5 demo clients", volume: "37.6 GB", health: 100 },
    { name: "Manual Upload", icon: "upload", status: "Ready", detail: "Resumable upload", volume: "—", health: 100 }
  ],
  cases: [
    { id: "CASE-DEMO-0421", name: "Financial Activity Review", owner: "Demo Investigator B", status: "Active", evidence: 3724, alerts: 2, exports: 1, priority: "High", updated: "2 hours ago" },
    { id: "CASE-DEMO-0192", name: "Unauthorized Access Review", owner: "Demo Investigator A", status: "Active", evidence: 1284, alerts: 1, exports: 0, priority: "Critical", updated: "4 hours ago" },
    { id: "CASE-DEMO-0510", name: "Internal Device Examination", owner: "Demo Forensic Examiner", status: "Under Review", evidence: 428, alerts: 0, exports: 2, priority: "Medium", updated: "Yesterday" }
  ],
  activity: [
    { time: "11:04", action: "Legal Hold applied", subject: "EV-DEMO-0001", actor: "Demo Legal Reviewer", tone: "blue" },
    { time: "10:42", action: "Verification package generated", subject: "EXP-DEMO-0017", actor: "Demo Investigator A", tone: "green" },
    { time: "09:18", action: "Evidence viewed", subject: "EV-DEMO-0001", actor: "Demo Investigator A", tone: "gray" },
    { time: "08:51", action: "Integrity verification passed", subject: "EV-DEMO-0004", actor: "Verification Service", tone: "green" },
    { time: "08:15", action: "SIEM batch committed", subject: "BATCH-DEMO-0072", actor: "Secure Connector Service", tone: "blue" }
  ],
  exports: [
    { id: "EXP-DEMO-0017", caseId: "CASE-DEMO-0421", evidence: 14, size: "22.47 GB", created: "30 Jul 2026, 10:42 AST", requestedBy: "Demo Investigator A", status: "Verification Ready" },
    { id: "EXP-DEMO-0012", caseId: "CASE-DEMO-0192", evidence: 6, size: "4.88 GB", created: "29 Jul 2026, 15:09 AST", requestedBy: "Demo Investigator B", status: "Complete" },
    { id: "EXP-DEMO-0008", caseId: "CASE-DEMO-0510", evidence: 3, size: "42.83 GB", created: "28 Jul 2026, 17:20 AST", requestedBy: "Demo Forensic Examiner", status: "Complete" }
  ],
  users: [
    { name: "Demo Tenant Administrator", role: "Tenant Admin", mfa: "Verified", last: "Today, 10:18", access: "Privileged" },
    { name: "Demo Investigator A", role: "Investigator", mfa: "Verified", last: "Today, 09:42", access: "Case-scoped" },
    { name: "Demo Legal Reviewer", role: "Legal Reviewer", mfa: "Verified", last: "Yesterday, 18:31", access: "Hold approvals" },
    { name: "Demo External Reviewer", role: "Guest Reviewer", mfa: "Verified", last: "29 Jul 2026", access: "Time-limited" }
  ],
  controls: [
    { name: "Immutable Evidence Vault", status: "Healthy", detail: "Compliance Mode policy active", icon: "lock" },
    { name: "Integrity Verification", status: "Healthy", detail: "SHA-512 verification service", icon: "fingerprint" },
    { name: "Tenant Isolation", status: "Healthy", detail: "Authorization filters enforced", icon: "building" },
    { name: "Key Custody", status: "Healthy", detail: "KMS-rooted custody controls", icon: "key" },
    { name: "MFA & RBAC", status: "Healthy", detail: "Step-up for sensitive actions", icon: "users" },
    { name: "Audit & Custody Signing", status: "Healthy", detail: "Signed custody events", icon: "shield-check" }
  ],
  editions: [
    { name: "Evidence Vault", label: "Foundation", description: "Core evidence preservation, integrity verification and custody timeline.", features: ["Immutable evidence preservation", "SHA-512 verification", "Chain of custody", "Core technical export", "Tenant RBAC"] },
    { name: "Evidence Trust", label: "Professional", description: "Advanced investigation, Legal Hold, SSO and offline verification workflows.", features: ["Everything in Evidence Vault", "Case Workspace", "Legal Hold", "Enterprise SSO", "Offline verification", "Advanced reporting"] },
    { name: "Sovereign Enterprise", label: "Regulated", description: "Enhanced governance and sovereign controls for regulated organizations.", features: ["Everything in Evidence Trust", "Advanced key custody", "Private connectivity option", "Service governance", "Custom integrations", "Enhanced support model"] },
    { name: "Strategic Dedicated", label: "Mission Critical", description: "Dedicated architecture options for strategic and large-scale workloads.", features: ["Dedicated isolation options", "Custom custody model", "Custom recovery design", "Named service team", "Executive governance", "Custom acceptance plan"] }
  ],
  technical: {
    endpoints: [
      ["POST", "/api/v1/evidence/upload/init", "Initiate tenant-bound resumable upload", { session_id: "UP-DEMO-8C0F", chunk_size_bytes: 67108864, max_object_bytes: 50000000000, status: "READY" }],
      ["POST", "/api/v1/evidence/upload/{session}/finalize", "Encrypt, commit under WORM, timestamp and verify", { evidence_id: "EV-DEMO-0099", profile: "TV-ENC-001-A-v1.0", worm: "COMPLIANCE", integrity: "SHA-512 VERIFIED" }],
      ["GET", "/api/v1/evidence/{id}/download", "Authorized tenant-bound decrypted stream", { status: "AUTHORIZED_STREAM", audit_event: "AUD-DEMO-8821" }],
      ["POST", "/api/v1/evidence/{id}/presigned-url", "Create TTL-bound read-only access URL", { ttl_seconds: 300, access: "READ_ONLY", audit_event: "AUD-DEMO-8822" }],
      ["POST", "/api/v1/evidence/{id}/evidence-package", "Generate portable technical evidence package", { package_id: "EXP-DEMO-0021", manifest: "INCLUDED", custody_report: "INCLUDED", status: "VERIFICATION_READY" }],
      ["GET", "/api/v1/integrity/{id}/verify", "Verify SHA-512, timestamp and custody signatures", { sha512: "MATCH", timestamp_token: "VALID", custody_signatures: "VALID", result: "VERIFIED" }],
      ["GET", "/api/v1/integrity/{id}/chain", "Return append-only chain of custody", { events: 7, hash_chain: "VALID", signature_profile: "Ed25519" }],
      ["GET", "/api/v1/audit/events", "Query tenant-filtered audit events", { page: 1, page_size: 50, total: 28431, authorization_filter: "ENFORCED" }],
      ["POST", "/api/v1/tenants", "Create tenant through an admin workflow", { tenant_id: "TEN-DEMO-BRAVO", status: "PENDING_POLICY_APPROVAL" }],
      ["POST", "/api/v1/tenants/{id}/data-subject-request", "Route privacy request to legal/retention review", { request_id: "DSR-DEMO-0142", status: "LEGAL_REVIEW_REQUIRED", automatic_deletion: false }],
      ["GET", "/api/v1/auth/oidc/{tenant}/login", "Start tenant-aware OIDC / enterprise SSO", { tenant_context: "BOUND", mfa_policy: "REQUIRED" }]
    ],
    tests: [
      ["tenant", "Cross-tenant evidence access", "Use a valid identity from another tenant", "TV-TENANT-403", "HTTP 403 — Forbidden", "Tenant context, database policy and cryptographic namespace did not match. No evidence metadata was disclosed."],
      ["missing", "Missing encrypted chunk", "Remove one authenticated chunk", "ENC-6A", "VERIFICATION FAILED", "Expected chunk count and whole-evidence SHA-512 did not match. Evidence was not accepted."],
      ["reorder", "Reordered encrypted chunks", "Change the order of two 64 MiB chunks", "ENC-6B", "AUTHENTICATION FAILED", "Chunk index and authenticated sequence validation failed."],
      ["substitute", "Cross-evidence substitution", "Insert a chunk from another evidence ID", "ENC-6C", "AAD CONTEXT MISMATCH", "Tenant ID, evidence ID and chunk context did not match the authenticated envelope."],
      ["unwrap", "Unauthorized Vault Transit unwrap", "Use an unapproved workload identity", "TV-VAULT-403", "POLICY DENIED", "The workload identity had no unwrap authority for the tenant namespace and key version."],
      ["expired", "Expired evidence access URL", "Use a TTL-bound URL after expiry", "TV-ACCESS-401", "HTTP 401 — Expired", "The signed grant expired. A new authorized workflow and audit event are required."]
    ],
    domains: [
      ["lock", "Immutable Evidence Preservation", "Compliance-mode retention, versioning, access logging and explicit delete/modify rejection.", ["WORM / Object Lock", "Version history", "Legal Hold protection", "Blocked bypass attempts"], "Simulated"],
      ["key", "Provider-Separated Encryption", "Per-evidence envelope encryption with tenant-bound Vault Transit protection.", ["AES-256-GCM", "64 MiB authenticated chunks", "Wrapped DEK", "KMS root / Vault separation"], "Detailed"],
      ["fingerprint", "Integrity & Time Provenance", "Deterministic verification of the complete original evidence stream.", ["SHA-512", "RFC 3161 token", "Ed25519 custody signing", "Offline verification"], "Simulated"],
      ["building", "Tenant Isolation", "Tenant context across identity, database policy, cryptographic namespace and exports.", ["Schema-per-tenant", "Row-Level Security", "Authorization filtering", "Negative tests"], "Simulated"],
      ["link", "Chain of Custody", "Append-only actor, action, time, reason and integrity references.", ["Signed events", "Tamper-evident ordering", "Legal Hold actions", "Export lineage"], "Detailed"],
      ["globe", "Saudi Sovereign Boundary", "Target Saudi residency for evidence, data-bearing logs, backups and derived content.", ["Private service paths", "Region controls", "Controlled administration", "Residency evidence"], "Acceptance-gated"],
      ["code", "Application & Integration APIs", "Versioned interfaces for upload, retrieval, verification, custody and privacy.", ["Resumable upload", "S3-compatible intake", "OIDC / M2M", "HLS/DASH retrieval"], "Interactive"],
      ["activity", "Security Operations", "Coordinated incident command, telemetry, evidence preservation and recovery.", ["One incident timeline", "Crypto escalation", "Restore evidence", "Release rollback"], "Interactive"],
      ["sparkles", "AI-Derived Analysis", "Phase 2 OCR, PII, classification and semantic search remain derived analysis.", ["Run provenance", "Human review", "Tenant-aware indexes", "No authority transfer"], "Phase 2"]
    ],
    aiRun: {
      analysis_run_id: "AIRUN-DEMO-20260802-0047",
      tenant_id: "TEN-DEMO-ALPHA",
      evidence_id: "EV-DEMO-0003",
      feature_id: "F-150 / F-151 / F-152 / F-153",
      model_profile: "rm-demo-ar-en-doc-v0.4",
      model_version: "2026.08-demo",
      environment: "PUBLIC-CONCEPT-DEMO",
      application_build: "demo-current",
      status: "COMPLETED",
      reviewer_status: "PENDING HUMAN REVIEW"
    },
    securityEvents: [
      ["11:04", "Blocked evidence deletion", "TV-WORM-403"],
      ["10:16", "Cross-tenant request denied", "TV-TENANT-403"],
      ["09:44", "Vault unwrap policy denied", "TV-VAULT-403"],
      ["08:30", "Restore verification passed", "RECOVERY-VERIFIED"]
    ]
  }
};
